language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
branches:
  only:
  - master
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y default-jdk && sudo apt-get install -y cmake; fi
  - g++ --version
  - clang++ --version
  - java -version

script: cmake . && make
